name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests and generate report
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: |
          npx playwright test

      - name: Upload debugging artifacts (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            global-setup-error.png
            test-results/
          retention-days: 7

      - name: Upload Playwright HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./playwright-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Post GitHub Pages URL in workflow summary
        run: echo "✅ [View Playwright Report](https://amruth-balbail.github.io/playwrightTests/)" >> $GITHUB_STEP_SUMMARY
